version: "3"

services:
  database:
    build:
      context: ../database
      dockerfile: Dockerfile
    volumes:
      - ../database/data:/var/lib/mysql
      - ../database/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ../database/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}