version: "3"

services:
  server:
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
    - ../src:/go/src/github.com/Uwasaru/Sayka
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - APIKEY=${APIKEY}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
      - PORT=${PORT}
      - GITHUB_ID=${GITHUB_ID}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GITHUB_CALLBACK_API=${GITHUB_CALLBACK_API}
      - GITHUB_GETME=${GITHUB_GETME}
      - rawPrivKey=${rawPrivKey}
